//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;
//using Autodesk.Revit.Attributes;
//using Autodesk.Revit.DB;
//using Autodesk.Revit.UI;

//namespace AMBRevitLibrary
//{
//    public static class Active
//    {
//        public static ExternalCommandData commandData;
       

//        //get application
//        var uiApp = commandData.Application;
//        var app = uiApp.Application;

//        //get UI document
//        var uiDoc = commandData.Application.ActiveUIDocument;

//        //get document
//        var doc = uiDoc.Document;


//        public static App Application
//        {

//        }
//    }
//}
